### ISSUE TITLE
编写您的第一个 Flutter App - Flutter中文网

### ISSUE THREAD

**Issue by wendux** [wendux/flutter-comment#5]
https://www.flutterchina.club/get-started/codelab/

**Comment by CK875430315** [comment]
使用白色主题，状态栏变成了深色字体这个是自动改变的吗？

**Comment by wendux** [comment]
@CK875430315 是的。

**Comment by baiyinshi** [comment]
第四步的第五点应该是Startup_namer 工程了，怎么又串到Myapp了。

**Comment by ghost** [comment]
@baiyinshi ``class MyApp extends StatelessWidget {`` 是这个 Myapp

**Comment by inlove2010** [comment]
第5步: 添加交互
在我手机上tap，整个row消失了，而不是点亮红心，为什么？

**Comment by inlove2010** [comment]
我自己搞错了，_saved是个set<>,我把它定义成了[]

**Comment by xster** [comment]
@CK875430315 可参考
https://github.com/flutter/flutter/blob/e77cfcf2ae95111cd1c8761e69ac6e19b10ba0b9/packages/flutter/lib/src/material/app_bar.dart#L349

**Comment by paizxin** [comment]
在Android Studio中拉取不到english_words: ^3.1.0这个库

**Comment by uni-cstar** [comment]
为什么我编译运行的效果，favor图标的颜色是填充的灰色而不是示例图中的红色呢？

**Comment by Maoxiai** [comment]
OK 完成(～￣▽￣)～

**Comment by baiyinshi** [comment]
@paizxin  你贴出你的pubspce.yaml 看看你的引用格式

**Comment by rocwong-cn** [comment]
:bread: **Done ！！！**

**Comment by billdai998** [comment]
问一下，关于右上面有一个debug的字样，这个怎么去掉？

**Comment by aizhuzi** [comment]
添加English_words 包提示： --no-color package get

**Comment by aizhuzi** [comment]
求帮忙，遇到没法导入包的问题，卡住了，@paizxin ，解决没？我直接复制pubspce.yaml文件内容也没法导包成功。

**Comment by itchaosfun** [comment]
在上述示例中,仿照这卸了一下,在页面来回多次快速切换的时候,会发生卡死并闪退的情况,这个问题是如何产生的呢?该怎么样修复?不知道大家是否遇到过~

**Comment by junlandroid** [comment]
`第一天学习 ，留个名`

**Comment by hellosweetmain1** [comment]
更换主题后，下拉那个波纹还是 淡蓝色的，没有跟随主题变化，还有就是返回主页面的时候感觉挺卡的，我的手机是 xiaomi 6 ，不知道这是不是正常的

**Comment by rongyanguapi** [comment]
学习了，和楼上一样，滑动列表明显感觉不很流畅，三星s8

**Comment by ei8Z** [comment]
同楼上，列表页滑动明显不流畅，华为p10

**Comment by wendux** [comment]
@ei8Z release 版本会流畅很多， 可以试试

**Comment by SoulJaZhao** [comment]
非常棒的教程，一步一步完成了demo

**Comment by ZhangWren** [comment]
第4步: 创建一个无限滚动ListView中的  2.  中的注释：在奇数行，该行书湖添加一个分割线widget，来分隔相邻的词对。
中的书湖是不是写错了？

**Comment by WeihuaGu** [comment]
上面说怎么去掉右上角的debug的，我用`grep -R "debug" ./android `命令发现了这一行：
./android/local.properties:flutter.buildMode=debug
我猜肯定是改成release就好了

**Comment by billdai998** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
build --release 就可以了



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.6;
        }
    

    
        font{
            line-height: 1.6;
        }
    
戴瑜billdai@foxmail.com


                



    在2018年06月22日 17:42，顾玮华<notifications@github.com> 写道： 


上面说怎么去掉右上角的debug的，我用grep -R "debug" ./android命令发现了这一行：
./android/local.properties:flutter.buildMode=debug
我猜肯定是改成release就好了

**Comment by newUserdd** [comment]
第一天学习，跟着撸了一遍下來，虽然还不了解dart语法，但感觉还不错的样子，现在蒙圈中....

**Comment by reply-1988** [comment]
在第三步中 Stateful widgets maintain state that might change during the lifetime of the widget. Implementing a stateful widget requires at least two classes: 1) a StatefulWidget class that creates an instance of 2) a State class. The StatefulWidget class is, itself, immutable, but the State class persists over the lifetime of the widget.
其中 but the State class persists over the lifetime of the widget感觉翻译成是在其生命周期中是可变的比较好

**Comment by KomoriWu** [comment]
ok,敲完了。收获满满

**Comment by Sunyc666** [comment]
已经成功的做出来了，倍感欣慰

**Comment by WeihuaGu** [comment]
请教一个问题，一个statefulwidget 创建了一个 与之绑定的State,其实就是拱手把构建的权力交给了State,并且二者的生命周期明显statefulwidget小于State,那外部怎么获得State保存的这些状态呢？应该不能从statefulwidget来获得吧，但是与其它widget结合时用的都是statefulwidget。

比如例子中，它把包含跳转页面的appbar都定义在了state中，所以可以直接调用_pushSaved()方法，而一但把它定义在外部，那么怎么访问被state保护的_saved变量？

**Comment by WeihuaGu** [comment]
@WeihuaGu
自问自答，关于这个，写了一篇[短文](https://www.jianshu.com/p/6c4c8812e706)。
我的理解，不一定对，也还是会总错的。

**Comment by wendux** [comment]
@WeihuaGu 如果想在外部引用state内的变量， 可以给widget设置一个GlobalKey, 然后通过这个key可以获取state 对象， 这样就可以访问状态了。

**Comment by WeihuaGu** [comment]
@wendux 感谢解答，感觉这个就像原生开发中通过R获得控件唯一的id有点像。

**Comment by asdasadasf** [comment]
debug版本的滑动不太流畅，还有就是跳转到save界面后，返回到第一个页面，感觉会卡顿了一下. Pixel Android 9.

**Comment by Alphrye** [comment]
debug版本的滑动不太流畅，还有就是跳转到save界面后，返回到第一个页面，感觉会卡顿了一下. Pixel Android 9.

**Comment by OC0311** [comment]
哈哈  照着写出来了，虽然只知道大概的意思

**Comment by zzzsssbo** [comment]
@Alphrye 是的 我的也会卡顿 而且主题颜色改变后 波纹颜色没有跟着改变

**Comment by heygays** [comment]
这语法太锤子了

**Comment by akkuan** [comment]
列表滑动起来好卡啊、、、小米max2

**Comment by wendux** [comment]
@DearAKuan release版本就好了


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by zouzhenglu** [comment]
为什么我这边的导航是做对齐的，不是居中的？？

**Comment by LT13S** [comment]
快速滑动，明显感到卡顿，Android手机略好，iPhone手机体验不如Android

**Comment by hatjs880328s** [comment]
Xcode怎么用啊？

**Comment by hatjs880328s** [comment]
如何使用XCODE开发  这个东西呢、

**Comment by WeihuaGu** [comment]
再请教一个问题，我写了个从url获取一个json的返回。用了dio.get这个函数，然后调用这个函数需要await,然后因为用了await，函数外面又要加async。而要调用这个函数，因为加了async,又要加await,因为加了await又要定义时外面加async,然后就无穷无尽了……，天那
如果我想测试这个getLiveLIst函数：
```
class XXX{

final url="http://XXX";

getLiveList() async{
        Dio dio = new Dio();
        Response<String> response=await dio.get(url);
        return response.data;

}

```
然后我在test文件夹下写了测试：
```
import 'package:test/test.dart';
import 'package:XXX/XXX.dart';
void main() {
  test('test get json', () {
   print( new XXX().getJson());
  });
}
```
当然，因为getJson加了async，print的结果是Instance of 'Future'
但是我想print json啊，怎么办，难道是：
```
import 'package:test/test.dart';
import 'package:XXX/XXX.dart';
void main() {
  test('test get json', () {
   print( await new XXX().getJson());
  });
}
```
当然了，它会报错，那我只能再加async
```
import 'package:test/test.dart';
import 'package:XXX/XXX.dart';
void main() {
  test('test get json', () async {
   print( await new XXX().getJson());
  });
}
```
当然了它会报错，因为有了async,所以要给test前面加 await,当然了它会报错，因为有了await,我需要给main函数加async.
```
import 'package:test/test.dart';
import 'package:XXX/XXX.dart';
void main() async{
  await test('test get json', () async {
   print( await new XXX().getJson());
  });
}
```
当然了，它会报错，然后我疯了

**Comment by wendux** [comment]
@WeihuaGu    哈哈，不用那么麻烦，不就想打印一行日志么:
```dart
new XXXI(). GetJson() .then((r)=>print(r))
```


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by WeihuaGu** [comment]
@wendux 
当我使用这样的形式时，then好像没有被执行
```
test('live list unit test', ()async{
        print("get json list unit start test");
        new XXX().getJson().then((jsonlist){
                print("the json is ");
                print(jsonlist);
        });

  });
```
因为只打出了"get json list unit start test"，"the json is" 和jsonlist并没有任何的输出
当我改成这样
```
test('live list unit test', ()async{
        print("get json list unit start test");
        var jsonlist=await new XXX().getJson();
        print(jsonlist);
  });
```
正确返回了json
```
live list unit start test
{"ret":200,"data":{"code":0,"msg":"","info":[{XXX},{XXX},{XXX}]}}
```

**Comment by wendux** [comment]
@WeihuaGu 话说我貌似没有看到你的getJson方法


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by WeihuaGu** [comment]
@wendux 
```
getJson() async{
        var httpClient = new HttpClient();
  	var uri = new Uri.http(urlhost,urlpath);
	try {
  	var request = await httpClient.getUrl(uri);
  	var response = await request.close();
  	var responseBody = await response.transform(UTF8.decoder).join();
	return responseBody;
	}catch (exception) {
      		print('Failed');
         }

}
```

**Comment by wendux** [comment]
@WeihuaGu 你可以参考一下dio vm分支的test.dart 里面都是异步请求，有打日志的代码


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by WeihuaGu** [comment]
@wendux 好的，我去看看。我只是觉得奇怪，因为刚学这个，进行异步操作是感觉时灵时不灵的。

感谢你耐心的回复：）。

**Comment by WeihuaGu** [comment]
一个text的widget怎么能允许用户进行文字选择，如果是安卓，只需要一个属性就行了，但是flutter找了一圈也没找到，只找到了一个叫做“RenderEditable"的类，但看文档没看明白怎么用。
允许用户选择文字是很基础的功能，比如这个示例中用户可能会想选择复制被标记的喜欢的名字，当然这可以通过给text的longPress添加复制来实现，但是用户想选择一部分，该怎么办呢？
flutter有没有提供方便的允许文字被选择的功能？

**Comment by wendux** [comment]
@WeihuaGu 这个问题我之前在flutter项目下提过issue提过， 但到目前为止还没有什么明确的解决方案


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by WeihuaGu** [comment]
@wendux 我看到有人一年前就提过这个issue,开发者说会把这个加入list,都一年了，哭晕啊……

**Comment by jiangbing0125** [comment]
列表刷动停止明显出现卡动

**Comment by jiangbing0125** [comment]
《如果你遇到了问题，请查看以下链接中应用程序的最终代码》 这种方式很赞

**Comment by duanpf** [comment]
不错

**Comment by vincentwu08** [comment]
签到！

**Comment by yangxiaoge** [comment]
学习了，成功体验了 flutter，对于需要上手来说还需要学习下 Dart，对于有时间的同学还是可以尝试的，毕竟 google 爸爸的产品。

**Comment by chenjzcj** [comment]
开始学习中，加油

**Comment by BingKui** [comment]
开始打怪升级之路啊~~~~

**Comment by Chainson** [comment]
怎么生成 release 版?

**Comment by QuestG** [comment]
之前一直想体验flutter， 如今按照指导敲了下代码，表达一下欣喜。没想到一百行左右的代码就实现了ListView的功能。

**Comment by y1990** [comment]
mark

**Comment by msdx** [comment]
错别字：`对其` -> `对齐`

**Comment by LinmingDart** [comment]
有没有群，求群号 class RandomWordsState extends State<RandomWords> {
  final _suggestions = <WordPair>[]; 这里<WordPair>[]是什么意思        ；class RandomWordState extend State <RandomWords>里的<RandomWords>是什么意思呢？小白求指点  跪谢

**Comment by humanheima** [comment]
还可以这样跳转，也是厉害

**Comment by Randyshu2018** [comment]
flutter packages get ...error
full logs likes below:
The setter 'readEventsEnabled=' was called on null.
Receiver: null
Tried calling: readEventsEnabled=false
package:pub/src/source/hosted.dart 344:7           BoundHostedSource._throwFriendlyError
package:pub/src/source/hosted.dart 144:7           BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
dart:async                                         _AsyncAwaitCompleter.completeError
package:pub/src/source/hosted.dart                 BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
dart:async                                         _asyncErrorWrapperHelper
package:pub/src/source/hosted.dart                 BoundHostedSource.doGetVersions
package:pub/src/source.dart 168:12                 BoundSource.getVersions
package:pub/src/solver/package_lister.dart 76:44   PackageLister._versions.<fn>.<fn>
dart:async                                         runZoned
package:pub/src/http.dart 275:10                   withDependencyType
package:pub/src/solver/package_lister.dart 75:33   PackageLister._versions.<fn>
===== asynchronous gap ===========================
dart:async                                         _asyncThenWrapperHelper
package:pub/src/utils.dart                         minByAsync
package:pub/src/solver/version_solver.dart 351:25  VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
dart:async                                         _asyncThenWrapperHelper
package:pub/src/solver/version_solver.dart         VersionSolver.solve
package:pub/src/solver.dart 35:10                  resolveVersions.<fn>
package:pub/src/log.dart 378:18                    progress
package:pub/src/solver.dart 32:10                  resolveVersions
package:pub/src/entrypoint.dart 210:24             Entrypoint.acquireDependencies
---- Log transcript ----
FINE: Pub 2.0.0
MSG : Resolving dependencies...
SLVR: fact: startup_namer is 0.0.0
SLVR: derived: startup_namer
SLVR: fact: startup_namer depends on cupertino_icons ^0.1.2
SLVR: fact: startup_namer depends on flutter any from sdk
SLVR: fact: startup_namer depends on english_words ^3.1.0
SLVR: fact: startup_namer depends on flutter_test any from sdk
SLVR:   selecting startup_namer
SLVR:   derived: flutter_test any from sdk
SLVR:   derived: english_words ^3.1.0
SLVR:   derived: flutter any from sdk
SLVR:   derived: cupertino_icons ^0.1.2
IO  : Get versions from https://dart-pub.mirrors.sjtug.sjtu.edu.cn//api/packages/english_words.
IO  : HTTP GET https://dart-pub.mirrors.sjtug.sjtu.edu.cn//api/packages/english_words
    | Accept: application/vnd.pub.v2+json
    | user-agent: Dart pub 2.0.0
SLVR: Version solving took 0:00:00.190301 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (0.1s).
ERR : The setter 'readEventsEnabled=' was called on null.
    | Receiver: null
    | Tried calling: readEventsEnabled=false
FINE: Exception type: NoSuchMethodError
ERR : package:pub/src/source/hosted.dart 344:7           BoundHostedSource._throwFriendlyError
    | package:pub/src/source/hosted.dart 144:7           BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                         _AsyncAwaitCompleter.completeError
    | package:pub/src/source/hosted.dart                 BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncErrorWrapperHelper
    | package:pub/src/source/hosted.dart                 BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 168:12                 BoundSource.getVersions
    | package:pub/src/solver/package_lister.dart 76:44   PackageLister._versions.<fn>.<fn>
    | dart:async                                         runZoned
    | package:pub/src/http.dart 275:10                   withDependencyType
    | package:pub/src/solver/package_lister.dart 75:33   PackageLister._versions.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncThenWrapperHelper
    | package:pub/src/utils.dart                         minByAsync
    | package:pub/src/solver/version_solver.dart 351:25  VersionSolver._choosePackageVersion
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | package:pub/src/solver.dart 35:10                  resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                    progress
    | package:pub/src/solver.dart 32:10                  resolveVersions
    | package:pub/src/entrypoint.dart 210:24             Entrypoint.acquireDependencies
---- End log transcript ----

**Comment by chengxianghe** [comment]
@aizhuzi  @paizxin Android Studio中拉取不到english_words: ^3.1.0 可以尝试用命令行操作“flutter packages get”

**Comment by adevjoe** [comment]
很详细了，继续学习

**Comment by EchoZuo** [comment]
问一下，关于右上面有一个debug的字样，这个怎么去掉？

**Comment by ErHu1993** [comment]
第一天学习~

**Comment by MrMJL** [comment]
Your application could not be compiled, because its dependencies could not be established.
Could not read "D:\work_space\zy\flutter_app\lib\main.dart" when determining Dart dependencies.

编译demo时候遇到的，这个问题，环境也重装过，一直都是这样子，读取权限也是有的。各位，求解惑啊。

**Comment by LIU1462056566** [comment]
english_words: ^3.1.0。使用这个包 我的模拟器就会隐藏起来，什么原因啊！

**Comment by ljybill** [comment]
我在学习中发现修改_biggerFont 的 fontSize 并不会热更新，需要Stop后再run，没想明白具体的原因

**Comment by noblewoman** [comment]
@billdai998 在 class MyApp 中 添加 debugShowCheckedModeBanner ： false。

**Comment by NoelBiao** [comment]
列表滑动起来，抖抖的感觉，华为美腿20 Pro

**Comment by ghlailq** [comment]
已完成

**Comment by Weiyi-C** [comment]
# 第四步代码注释中出现错字

BUG位置：[第4步: 创建一个无限滚动ListView](https://flutterchina.club/get-started/codelab/#%E7%AC%AC4%E6%AD%A5-%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E6%97%A0%E9%99%90%E6%BB%9A%E5%8A%A8listview) 第2条
> 2. 向RandomWordsState类添加一个 _buildSuggestions() 函数... 

的代码示例中，第8行的注释文本中“该函数会添加一个”被打成了“该行书湖添加一个”

```
// 在偶数行，该函数会为单词对添加一个ListTile row.  
// 在奇数行，该行书湖添加一个分割线widget，来分隔相邻的词对。
```

**Comment by Weiyi-C** [comment]
# 第5步: 添加交互 高亮的行缺失
BUG位置：[第5步: 添加交互](https://flutterchina.club/get-started/codelab/#%E7%AC%AC5%E6%AD%A5-%E6%B7%BB%E5%8A%A0%E4%BA%A4%E4%BA%92) 第3条

> 3. 同时在 _buildRow()中， 添加一个心形 ❤️ 图标到 ListTiles以启用收藏功能...

的代码示例中，第2行代码也是新添加的代码，但是没有高亮

``` dart
Widget _buildRow(WordPair pair) {
  final alreadySaved = _saved.contains(pair); // 该行也是新添加的代码，但是没有高亮
  return new ListTile(
    title: new Text(
      pair.asPascalCase,
      style: _biggerFont,
    ),
    trailing: new Icon(
      alreadySaved ? Icons.favorite : Icons.favorite_border,
      color: alreadySaved ? Colors.red : null,
    ),
  );
}
```

**Comment by daniuwo** [comment]
很棒,我也完成了第一个 app
honor v9 测试很流畅

**Comment by noblewoman** [comment]
> 问一下，关于右上面有一个debug的字样，这个怎么去掉？
设置 debugShowCheckedModeBanner 为false

class MyApp extends StatelessWidget{
  @override
  Widget build(BuildContext context){
    return new MaterialApp(
      debugShowCheckedModeBanner: false,
    );
  }
}

**Comment by xiaowanduo** [comment]
> 问一下，关于右上面有一个debug的字样，这个怎么去掉？

打release包后应该就消失了。

**Comment by houyanbing** [comment]
这一节跟着敲完了，但是懵懵懂懂的。。。大概能明白代码意思，但是自己写不出来

**Comment by DengQiSong** [comment]
跟着敲完了代码、意思差不多都理解了、不过代码风格和原生安卓确实不一样、还需要在多敲一点。

**Comment by FlappyQingniao** [comment]
> 在Android Studio中拉取不到english_words: ^3.1.0这个库
因为3.1.0已经过期了，可以到官方拉取最新的

**Comment by chao9267** [comment]
> 在Android Studio中拉取不到english_words: ^3.1.0这个库

windows     android studio遇到同样的问题  使用flutter pakeages get命令也无效

**Comment by wangjing013** [comment]
> > 在Android Studio中拉取不到english_words: ^3.1.0这个库
> 
> windows android studio遇到同样的问题 使用flutter pakeages get命令也无效

把默认的 package 获取地址改为访问没有问题的镜像站就可以， 可以添加两个环境变量，今天上午搭建环境也遇到这个问题

PUB_HOSTED_URL    https://pub.flutter-io.cn
FLUTTER_STORAGE_BASE_URL   https://storage.flutter-io.cn

**Comment by MisterZhu** [comment]
你好，flutter项目是否有类似iOS的.pch文件？进行全局引用头文件功能？如果我的Flutter项目要迁移到WEB端，lib路径下dart文件中的相关引都要修改，岂不是每个dart文件的引用（import 'package:flutter/material.dart'）都要改成（import 'package:flutter_web/material.dart'）？这样好麻烦呀。

**Comment by wangxianbiao** [comment]
> > > 在Android Studio中拉取不到english_words: ^3.1.0这个库
> > 
> > 
> > windows android studio遇到同样的问题 使用flutter pakeages get命令也无效
> 
> 把默认的 package 获取地址改为访问没有问题的镜像站就可以， 可以添加两个环境变量，今天上午搭建环境也遇到这个问题
> 
> PUB_HOSTED_URL https://pub.flutter-io.cn
> FLUTTER_STORAGE_BASE_URL https://storage.flutter-io.cn

你好，我在环境变量里加了这两个也不行，提示以下异常，这要怎么解决啊。
>flutter packages get
Unhandled exception:
FormatException: Scheme not starting with alphabetic character (at character 1)
 https://pub.flutter-io.cn
^

#0      _Uri._fail (dart:core/uri.dart:1625:5)
#1      _Uri._makeScheme (dart:core/uri.dart:2186:7)
#2      new _Uri.notSimple (dart:core/uri.dart:1467:18)
#3      Uri.parse (dart:core/uri.dart:1024:17)
#4      HostedSource._pubHostedUrlConfig (package:pub/src/source/hosted.dart:57:19)
#5      HostedSource.defaultUrl (package:pub/src/source/hosted.dart:50:28)
#6      new UploaderCommand (package:pub/src/command/uploader.dart:27:42)
#7      new PubCommandRunner (package:pub/src/command_runner.dart:107:16)
#8      main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart:8:3)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
Running "flutter pub get" in flutter_app...
pub get failed (255; #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12))

**Comment by wangxianbiao** [comment]
> > > > 在Android Studio中拉取不到english_words: ^3.1.0这个库
> > > 
> > > 
> > > windows android studio遇到同样的问题 使用flutter pakeages get命令也无效
> > 
> > 
> > 把默认的 package 获取地址改为访问没有问题的镜像站就可以， 可以添加两个环境变量，今天上午搭建环境也遇到这个问题
> > PUB_HOSTED_URL https://pub.flutter-io.cn
> > FLUTTER_STORAGE_BASE_URL https://storage.flutter-io.cn
> 
> 你好，我在环境变量里加了这两个也不行，提示以下异常，这要怎么解决啊。
> 
> > flutter packages get
> > Unhandled exception:
> > FormatException: Scheme not starting with alphabetic character (at character 1)
> > https://pub.flutter-io.cn
> > ^
> 
> #0 _Uri._fail (dart:core/uri.dart:1625:5)
> #1 _Uri._makeScheme (dart:core/uri.dart:2186:7)
> #2 new _Uri.notSimple (dart:core/uri.dart:1467:18)
> #3 Uri.parse (dart:core/uri.dart:1024:17)
> #4 HostedSource._pubHostedUrlConfig (package:pub/src/source/hosted.dart:57:19)
> #5 HostedSource.defaultUrl (package:pub/src/source/hosted.dart:50:28)
> #6 new UploaderCommand (package:pub/src/command/uploader.dart:27:42)
> #7 new PubCommandRunner (package:pub/src/command_runner.dart:107:16)
> #8 main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/pub/bin/pub.dart:8:3)
> #9 _startIsolate. (dart:isolate-patch/isolate_patch.dart:305:32)
> #10 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
> Running "flutter pub get" in flutter_app...
> pub get failed (255; #10 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12))

问题解决了，在配置环境变量时，PUB_HOSTED_URL的值前面多了个空格，删掉后重启studio就好了

**Comment by WANG1020** [comment]
Packages get  这个 在那边看啊？

**Comment by x634725355** [comment]
我在子路由添加了一个点击删除当前选中的产品名字 但是点击之后数据改变了 但是并不会刷新 子路由页面    应该如何解决呢
![1594194693(1)](https://user-images.githubusercontent.com/40459345/86892604-0e8f8100-c133-11ea-836a-c0c2234810ff.png)

**Comment by ghost** [comment]
Way to go !
