### ISSUE TITLE
在Flutter中构建布局 - Flutter中文网

### ISSUE THREAD

**Issue by wendux** [wendux/flutter-comment#9]
https://www.flutterchina.club/tutorials/layout/

**Comment by kingideayou** [comment]
对其 widgets -> 对齐 widgets

**Comment by sunnyBob** [comment]
使用github账号登陆 -> 登录

**Comment by bcc222** [comment]
第二张图片感觉很别扭，为啥横着排的叫 Column

**Comment by qiang437587687** [comment]
图片一直是报错的，请问那个仁兄能告诉我一下吗？

code build done.
Syncing files to device iPhone X...
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown resolving an image codec:
flutter: Unable to load asset: assets/lake.jpg
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
flutter: <asynchronous suspension>
flutter: #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:383:44)
flutter: <asynchronous suspension>


下面是 pubspec.yaml 里面配置图片的地方
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/lake.jpg

**Comment by crzaycat** [comment]
@qiang437587687  图片地址配置位置（- images/lake.jpg）和代码里引用的位置（ assets/lake.jpg）不一致

**Comment by iallai** [comment]
@bcc222  第二张图的意思是整个容器 看做一个Column 里面有4个ROW

**Comment by OptimusMX** [comment]
不知道其他同学遇没遇到button不显示的问题，其实是代码的颜色跟背景色一样导致的，修改color的颜色就可以显示了。

**Comment by EnvySongtao** [comment]
widget机制， 有点坑啊， 各种return不提示错误，运行就各种报错了

**Comment by zztiswb116** [comment]
点击代码 显示404  代码找不到了

**Comment by LinmingDart** [comment]
能出书吗？

**Comment by LIU1462056566** [comment]
我也是点击代码显示404，咋回事啊

**Comment by wendux** [comment]
@LinmingDart 书正在写，已经完成了一大半，敬请关注


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by lp7799** [comment]
GridView的瀑布式布局有介绍吗？

**Comment by gin-lsl** [comment]
@zztiswb116 @LIU1462056566 
新的地址在这里：https://raw.githubusercontent.com/flutter/website/master/src/_includes/code/layout/lakes/main.dart

可以在flutter.io查看链接地址。

**Comment by lessismore100** [comment]
第3步: 实现按钮行 中的代码应该是这个



```flutter
return MaterialApp(
      title: 'Flutter Layout Demo',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Top Lakes'),
        ),
        body: Column(
          children: [
            titleSection,
          ],
        ),
      ),
);
```


[official website source link](https://github.com/flutter/website/blob/master/examples/layout/lakes/step2/lib/main.dart)

**Comment by WangXi01** [comment]
flutter中文网上面main.dart代码的链接失效了，我找了下，正确的链接是[https://github.com/flutter/website/blob/master/examples/layout/lakes/step6/lib/main.dart](url)

**Comment by zhoujian521** [comment]
> 第二张图片感觉很别扭，为啥横着排的叫 Column

存放 4个Row的列 叫做 Column

**Comment by sharpyale** [comment]
flutter中文网上面main.dart代码的链接失效了，能否更新一下，或者提供一个新的地址。感谢！
